/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as AreasSlugRouteImport } from './routes/areas.$slug'
import { Route as ConsultantsIdRouteImport } from './routes/consultants.$id'
import { Route as FileIdRouteImport } from './routes/file.$id'
import { Route as PropertiesSlugRouteImport } from './routes/properties.$slug'
import { Route as VSlugIdRouteImport } from './routes/v.$slug.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const AreasSlugRoute = AreasSlugRouteImport.update({
  id: '/areas/$slug',
  path: '/areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultantsIdRoute = ConsultantsIdRouteImport.update({
  id: '/consultants/$id',
  path: '/consultants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FileIdRoute = FileIdRouteImport.update({
  id: '/file/$id',
  path: '/file/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesSlugRoute = PropertiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropertiesRoute,
} as any)
const VSlugIdRoute = VSlugIdRouteImport.update({
  id: '/v/$slug/$id',
  path: '/v/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/tracking': typeof TrackingRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/file/$id': typeof FileIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/v/$slug/$id': typeof VSlugIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/tracking': typeof TrackingRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/file/$id': typeof FileIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/v/$slug/$id': typeof VSlugIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/compare': typeof CompareRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/tracking': typeof TrackingRoute
  '/areas/$slug': typeof AreasSlugRoute
  '/consultants/$id': typeof ConsultantsIdRoute
  '/file/$id': typeof FileIdRoute
  '/properties/$slug': typeof PropertiesSlugRoute
  '/v/$slug/$id': typeof VSlugIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compare'
    | '/favorites'
    | '/properties'
    | '/tracking'
    | '/areas/$slug'
    | '/consultants/$id'
    | '/file/$id'
    | '/properties/$slug'
    | '/v/$slug/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/compare'
    | '/favorites'
    | '/properties'
    | '/tracking'
    | '/areas/$slug'
    | '/consultants/$id'
    | '/file/$id'
    | '/properties/$slug'
    | '/v/$slug/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compare'
    | '/favorites'
    | '/properties'
    | '/tracking'
    | '/areas/$slug'
    | '/consultants/$id'
    | '/file/$id'
    | '/properties/$slug'
    | '/v/$slug/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CompareRoute: typeof CompareRoute
  FavoritesRoute: typeof FavoritesRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  TrackingRoute: typeof TrackingRoute
  AreasSlugRoute: typeof AreasSlugRoute
  ConsultantsIdRoute: typeof ConsultantsIdRoute
  FileIdRoute: typeof FileIdRoute
  VSlugIdRoute: typeof VSlugIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/areas/$slug': {
      id: '/areas/$slug'
      path: '/areas/$slug'
      fullPath: '/areas/$slug'
      preLoaderRoute: typeof AreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultants/$id': {
      id: '/consultants/$id'
      path: '/consultants/$id'
      fullPath: '/consultants/$id'
      preLoaderRoute: typeof ConsultantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/file/$id': {
      id: '/file/$id'
      path: '/file/$id'
      fullPath: '/file/$id'
      preLoaderRoute: typeof FileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$slug': {
      id: '/properties/$slug'
      path: '/$slug'
      fullPath: '/properties/$slug'
      preLoaderRoute: typeof PropertiesSlugRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/v/$slug/$id': {
      id: '/v/$slug/$id'
      path: '/v/$slug/$id'
      fullPath: '/v/$slug/$id'
      preLoaderRoute: typeof VSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PropertiesRouteChildren {
  PropertiesSlugRoute: typeof PropertiesSlugRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesSlugRoute: PropertiesSlugRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CompareRoute: CompareRoute,
  FavoritesRoute: FavoritesRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  TrackingRoute: TrackingRoute,
  AreasSlugRoute: AreasSlugRoute,
  ConsultantsIdRoute: ConsultantsIdRoute,
  FileIdRoute: FileIdRoute,
  VSlugIdRoute: VSlugIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
